/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoescuelaswing;

import controlador.Controlador;
import ester.autoescuela.tipocarnet.TipoCarnet;
import java.awt.event.ActionListener;
import modelo.conexion.ConexionAutoescuela;
import vista.InterfazVista;

/**
 *
 * @author Formacion
 */
public class GestionAlumnos extends javax.swing.JFrame implements InterfazVista {

    private static final long serialVersionUID = -612577678585684133L;
    Controlador controlador;

    /**
     * Creates new form GestionAlumno
     */
    public GestionAlumnos() {
        ConexionAutoescuela cA = ConexionAutoescuela.getInstance();
        controlador = new Controlador(cA);
        initComponents();

        for (TipoCarnet carnet : TipoCarnet.values()) {
            jComboBoxTipoDeCarnet.addItem(carnet.name());
        }
        controlador.setVista(this);
    }

    @Override
    public void setId(int id) {
        datosAlumno1.getjTextFieldIdAlumno().setText(Integer.toString(id));
    }

    @Override
    public String getNombre() {
        return datosAlumno1.getjTextFieldNombre().getText();
    }

    @Override
    public String getAp1() {
        return datosAlumno1.getjTextFieldPrimerApellido().getText();
    }

    @Override
    public String getAp2() {
        return datosAlumno1.getjTextFieldSegundoApellido().getText(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getDNI() {
        return datosAlumno1.getjTextFieldDNI().getText(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getTlfn() {
        return datosAlumno1.getjTextFieldTelefono().getText(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getDia() {
         return Integer.parseInt(datosAlumno1.getjTextFieldDia().getText()); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getMes() {
          return Integer.parseInt(datosAlumno1.getjTextFieldMes().getText()); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getAnio() {
        return Integer.parseInt(datosAlumno1.getjTextFieldAnnio().getText());  //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public boolean getPresencial() {
        return datosAlumno1.getjComboBoxtipodeAlumno().getSelectedItem().toString().equals("Presencial"); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public TipoCarnet getCarnet() {
        String lo = (String) jComboBoxTipoDeCarnet.getModel().getSelectedItem();
       return TipoCarnet.valueOf(lo);   
    }

    
//    
//    public String getjComboBoxTipoDeCarnet() {
//        return 
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionAlum = new javax.swing.JTabbedPane();
        jPanelAltas = new javax.swing.JPanel();
        jLabelTipoDeCarnet = new javax.swing.JLabel();
        jComboBoxTipoDeCarnet = new javax.swing.JComboBox();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        datosAlumno1 = new autoescuelaswing.DatosAlumno();
        jPanelBajasYModif = new javax.swing.JPanel();
        jScrollInfoTabla = new javax.swing.JScrollPane();
        jTextTabla = new javax.swing.JTextArea();
        datosAlumno2 = new autoescuelaswing.DatosAlumno();
        jPanelConsult = new javax.swing.JPanel();
        jScrollInfoConsultas = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelBotones = new javax.swing.JPanel();
        jButtonModificar = new javax.swing.JButton();
        jButtonCrear = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonMostrarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Autoescuela");

        jLabelTipoDeCarnet.setText("Tipo de Carnet:");

        jComboBoxTipoDeCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDeCarnetActionPerformed(evt);
            }
        });

        jLabelPrecio.setText("Precio:");

        jTextFieldPrecio.setEditable(false);
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAltasLayout = new javax.swing.GroupLayout(jPanelAltas);
        jPanelAltas.setLayout(jPanelAltasLayout);
        jPanelAltasLayout.setHorizontalGroup(
            jPanelAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltasLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanelAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoDeCarnet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPrecio)
                    .addComponent(jComboBoxTipoDeCarnet, 0, 161, Short.MAX_VALUE))
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAltasLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(datosAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        jPanelAltasLayout.setVerticalGroup(
            jPanelAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanelAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoDeCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoDeCarnet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecio))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanelGestionAlum.addTab("Altas", jPanelAltas);

        jTextTabla.setColumns(20);
        jTextTabla.setRows(5);
        jScrollInfoTabla.setViewportView(jTextTabla);

        javax.swing.GroupLayout jPanelBajasYModifLayout = new javax.swing.GroupLayout(jPanelBajasYModif);
        jPanelBajasYModif.setLayout(jPanelBajasYModifLayout);
        jPanelBajasYModifLayout.setHorizontalGroup(
            jPanelBajasYModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBajasYModifLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(jPanelBajasYModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datosAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollInfoTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        jPanelBajasYModifLayout.setVerticalGroup(
            jPanelBajasYModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBajasYModifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollInfoTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanelGestionAlum.addTab("Bajas y Modificaciones", jPanelBajasYModif);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollInfoConsultas.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelConsultLayout = new javax.swing.GroupLayout(jPanelConsult);
        jPanelConsult.setLayout(jPanelConsultLayout);
        jPanelConsultLayout.setHorizontalGroup(
            jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jScrollInfoConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanelConsultLayout.setVerticalGroup(
            jPanelConsultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollInfoConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelGestionAlum.addTab("Consultas", jPanelConsult);

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");

        jButtonMostrarTodo.setText("Mostrar todo");

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonMostrarTodo)
                .addGap(45, 45, 45))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonMostrarTodo))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGestionAlum)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGestionAlum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        controlador.crearAlumno();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jComboBoxTipoDeCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDeCarnetActionPerformed
        String lo = (String) jComboBoxTipoDeCarnet.getModel().getSelectedItem();
        TipoCarnet t = TipoCarnet.valueOf(lo);
        jTextFieldPrecio.setText(Float.toString(t.getPrecio()));

    }//GEN-LAST:event_jComboBoxTipoDeCarnetActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private autoescuelaswing.DatosAlumno datosAlumno1;
    private autoescuelaswing.DatosAlumno datosAlumno2;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonMostrarTodo;
    private javax.swing.JComboBox jComboBoxTipoDeCarnet;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTipoDeCarnet;
    private javax.swing.JPanel jPanelAltas;
    private javax.swing.JPanel jPanelBajasYModif;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelConsult;
    private javax.swing.JTabbedPane jPanelGestionAlum;
    private javax.swing.JScrollPane jScrollInfoConsultas;
    private javax.swing.JScrollPane jScrollInfoTabla;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextArea jTextTabla;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(Controlador c) {
        this.controlador = c;
    }
}
